apiVersion: v1
kind: Service
metadata:
  name: "{{ meta.name }}-nginx"
  # TODO meta.namespace
  namespace: "default"
spec:
  type: "NodePort"
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    app: "{{ meta.name }}-nginx"
