apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hugosites.staticdocs
spec:
  group: staticdocs
  names:
    kind: HugoSite
    listKind: HugoSiteList
    plural: hugosites
    singular: hugosite
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
