apiVersion: static.docs/v1alpha1
kind: HugoSite
metadata:
  name: operator-sdk
spec:
  # Add fields here
  build_git_repo: "https://github.com/operator-framework/operator-sdk"
  github_docs_dir: "website"
